config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'user/index' => 'user#index'
  root 'user#index'
  get 'photo/index/:id' => 'photo#index', as: 'user_photos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all
    @user_all = User.all

  end
  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users=User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to 'Users', user_index_path,class:"navbar-brand" %>
  <!--  <a class="navbar-brand" href="#">Rails App</a>-->

  <form class="form-inline">
    <input class="form-control mr-sm-2" type="text" id="myInput" onkeyup="myFunction()" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" onclick="myFunction()">Search</button>
  </form>

  <script>
      function myFunction() {
          var input, filter, table, tr, td, i;
          input = document.getElementById("myInput");
          filter = input.value.toUpperCase();
          table = document.getElementById("myTable");
          tr = table.getElementsByTagName("tr");
          for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[0];
              if (td) {
                  if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                      tr[i].style.display = "";
                  } else {
                      tr[i].style.display = "none";
                  }
              }
          }
      }
  </script>

</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>PhotoSite App</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <br/>
  <%= yield %>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>

app/views/photo/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photo Site</title>
</head>


<body>
<center>
  <div style="...">
    <h1><u>Photos of Users with Comments</u></h1>
  </div>
  <br/>
  <div>
    <h2>Photos of <%= @user.first_name %> <%= @user.last_name %></h2>
    <% @photos.each do |photo| %>

      <p><%=image_tag(photo.file_name) %></p>
 <!--     <p><%=image_tag("https://photositeprojectimages.s3.amazonaws.com/"+photo.file_name) %></p> -->
      <p> photo created at <%= photo.date_time %></p>

      <% @comments.where("photo_id=?" ,photo.id).each do |comment| %>

        <li> comment: <%= comment.comment_text %></li>
        <li> created at: <%= comment.date_time %></li>
        <li> posted by: <%= link_to display_name(comment.user_id), user_photos_path(comment.user_id) %></li>

      <% end %>
      </ul>
      <br>
      <br>
    <%end%>
  </div>
</center>
</body>
</html>

app/views/user/index.html.erb
<h1>Users List</h1>
<body>

<table id="myTable" class="table table-striped table-hovered">
  <tr>
    <thead class="thead-dark">
    <th style="..."><h2>Index </h2></th>
    <th style="..."><h2>First Name </h2></th>
    <th style="..."><h2>Last Name</h2></th>
    </thead>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <th style="..."><%= link_to user.id, user_photos_path(user.id) %></th>
      <td style="..."><%= link_to user.first_name, user_photos_path(user.id) %></td>
      <td style="..."><%= link_to user.last_name,user_photos_path(user.id) %></td>
    </tr>
  <% end %>
</table>

</body>